<?php
include_once "panther.php";
include_once "dog.php";
include_once "lion.php";
include_once "dove.php";
include_once "Eagle.php";
include_once "owl.php";
include_once "tiger.php";
include_once "rabbit.php";
include_once "falcon.php";
include_once "deer.php";
include_once "Buffalo.php";
include_once "raven.php";
include_once "giraffe.php";
include_once "cows.php";
include_once "vulture.php";
include_once "parrot.php";
use Parrot\Parrot;
use Vulture\Vulture;
use Cows\Cows;
use Giraffe\Giraffe;
use Raven\Raven;
use Buffalo\Buffalo;
use Deer\Deer;
use Falcon\Falcon;
use Rabbit\Rabbit;
use Owl\Owl;
use Panther\Panther;
use Dog\Dog;
use Lion\Lion;
use Eagle\Eagle;
use Dove\Dove;
use Tiger\Tiger;
$objectOwl                  = new Owl;
$objectOwl->image           = "th.jfif";
$objectOwl->name            = "THE OWL";
$objectOwl->food            = "chim bé";
$objectOwl->speed           = "30km/h";
$objectOwl->weight          = "3kg";
$objectOwl->perSonaLity     = "khuôn mắt ngây thơ trong sáng tiếng kêu rợn gáy";
$objectPanther              = new Panther;
$objectPanther->image       = "Bao.jpg";
$objectPanther->name        = "THE PANTHER";
$objectPanther->food        = "thịt";
$objectPanther->speed       = "100km/h";
$objectPanther->weight      = "40kg";
$objectPanther->perSonaLity = "ngầu chất tốc độ làm chủ cuộc chơi";
$objectDog                  = new Dog;
$objectDog->image           = "doan-van-tham-khao-so-10-530005.jpg";
$objectDog->name            = "THE DOG";
$objectDog->food            = "thịt";
$objectDog->speed           = "30km/h";
$objectDog->weight          = "20kg";
$objectDog->perSonaLity     = "dễ thương đáng yêu";
$objectLion                 = new Lion;
$objectLion->image          = "lion-king-1-1563155068176555217978-15637834089391350227836-crop-15637834158711662738000.jpeg";
$objectLion->name           = "KING LION";
$objectLion->food           = "thịt";
$objectLion->speed          = "60km/h";
$objectLion->weight         = "60kg";
$objectTiger                = new Tiger;
$objectTiger->image         = "ho_an_thit_con_1_QBEO.png";
$objectTiger->name          = "THE TIGER";
$objectTiger->food          = "thịt";
$objectTiger->speed         = "70km/h";
$objectTiger->weight        = "80kg";
$objectTiger->perSonaLity   = "hung dữ nguy hiểm tốc độ vượt trội";
$objectEagle                = new Eagle;
$objectEagle->image         = "v2-72c732297cdf5d1291c101bed819cda3720w-16220189095601127267370.jpg";
$objectEagle->name          = "King Eagle";
$objectEagle->food          = "thịt";
$objectEagle->speed         = "70km/h";
$objectEagle->weight        = "3kg";
$objectEagle->perSonaLity   = "ánh mắt sắc lén thích chiến đấu với bão có í chí kiên cường";
$objectDove                 = new Dove;
$objectDove->image          = "20150923114929-cc4b.jpg";
$objectDove->name           = "THE DOVE";
$objectDove->speed          = "10km/h";
$objectDove->weight         = "30kg";
$objectDove->food           = "sâu,bọ, bánh mì,cơm";
$objectDove->perSonaLity    = "đẹp hiền lành dễ thương bình minh gợi sáng";
$objectVulture              = new Vulture;
$objectVulture->name        = "THE VULTURE";
$objectVulture->image       = "Vulture.jpg";
$objectVulture->food        = "xác chết";
$objectVulture->speed       = "20km/h";
$objectVulture->weight      = "5kg";
$objectVulture->perSonaLity = "Đây là loài chim săn mồi có mỏ hình móc cong sắc nhọn, đôi cánh khá dài";
$objectGiraffe              = new Giraffe;
$objectGiraffe->name        = "THE GIRAFFE";
$objectGiraffe->image       = "huucaoco1b.jpg";
$objectGiraffe->food        = "thực vật";
$objectGiraffe->speed       = "20km/h";
$objectGiraffe->weight      = "850kg";
$objectGiraffe->perSonaLity = "có chiếc cổ dài";
$objectRabbit               = new Rabbit;
$objectRabbit->name         = "THE RABBIT";
$objectRabbit->image        = "rabbit-breeds-american-white-1553635287.jpg";
$objectRabbit->food         = "thực vật";
$objectRabbit->speed        = "10km/h";
$objectRabbit->weight       = "5kg";
$objectRabbit->perSonaLity  = "là loài gia súc tương đối yếu";
$objectRaven                = new Raven;
$objectRaven->name          = "THE RAVEN";
$objectRaven->image         = "raven-bird.jpg";
$objectRaven->food          = "xác chết";
$objectRaven->speed         = "20km/h";
$objectRaven->weight        = "2kg";
$objectRaven->perSonaLity   = " cực kỳ thông minh dễ thương đáng yêu dễ gần ";
$objectBuffalo              = new Buffalo;
$objectBuffalo->name        = "THE BUFFALO";
$objectBuffalo->image       = "thuyet-minh-con-trau.jpg";
$objectBuffalo->food        = " thực vật ";
$objectBuffalo->speed       = " 20km/h ";
$objectBuffalo->weight      = " 800kg ";
$objectBuffalo->perSonaLity = " siêng nặng chăm chỉ hùng mãnh ";
$objFalCon                  = new Falcon;
$objFalCon->name            = "THE FALCON";
$objFalCon->image           = "420px-Accipiter_gentilisAAP045CA.jpg";
$objFalCon->food            = "thịt";
$objFalCon->speed           = "50km/h";
$objFalCon->weight          = "5kg";
$objFalCon->perSonaLity     = "him ưng là một trong những loài chim săn mồi lớn và sát thủ nhất ở trên bầu trời";
$objectDeer                 = new Deer;
$objectDeer->name           = "THE DEER";
$objectDeer->image          = "01d64da2-fbfe-11eb-aa37-9736ba6f9b4b_image_hires_043836.jpg";
$objectDeer->food           = "thực vật";
$objectDeer->speed          = "30km/h";
$objectDeer->weight         = "200kg";
$objectDeer->perSonaLity    = "Nai dễ thương ";
$objectCows                 = new Cows;
$objectCows->name           = "THE COWS";
$objectCows->image          = "tải xuống.jfif";
$objectCows->food           = " thực vật ";
$objectCows->speed          = " 30km/h ";
$objectCows->weight         = " 500kg ";
$objectCows->perSonaLity    = " siêng nặng chăm chỉ hùng mãnh ";
$objectParrot               = new Parrot;
$objectParrot->name         = "THE PARROT";
$objectParrot->image        = "p096tdsh.jpg";
$objectParrot->food         = " thực vật ";
$objectParrot->speed        = " 20km/h ";
$objectParrot->weight       = " 2kg ";
$objectParrot->perSonaLity  = "tính cách đáng yêu vui vẻ loài Vẹt ";
$objectGentle               = [];

$objectGentle[]             = $objectDog;
$objectGentle[]             = $objectDeer;
$objectGentle[]             = $objectCows;
$objectGood                 = [];
$objectGood[]               = $objectBuffalo;
$objectGood[]               = $objectGiraffe;
$objectGood[]               = $objectVulture;
$objectWild                 = [];
$objectWild[]               = $objectLion;
$objectWild[]               = $objectTiger;
$objectWild[]               = $objectPanther;
$objectBirdBig              = [];
$objectBirdBig[]            = $objectEagle;
$objectBirdBig[]            = $objFalCon;
$objectBirdBig[]            = $objectOwl;
$objectBirdSmall            = [];
$objectBirdSmall[]          = $objectParrot;
$objectBirdSmall[]          = $objectDove;
$objectBirdSmall[]          = $objectRaven;
include_once "html.php";











