<?php
include_once "cat.php";
include_once "Panther.php";
include_once "dog.php";
include_once "lion.php";
include_once "dove.php";
include_once "Eagle.php";
include_once "dinosaure.php";
include_once "owl.php";
include_once "tiger.php";
use Owl\Owl;
use Cat\Cat;
use Panther\Panther;
use Dog\Dog;
use Lion\Lion;
use Eagle\Eagle;
use Dove\Dove;
use Dinosaure\Dinosaure;
use Tiger\Tiger;
$objects                 = [];
$objectOwl               = new Owl;
$objectOwl->image        = "th.jfif";
$objectOwl->name         = "THE OWL";
$objectOwl->say          = "quoắc  quoắc  quoắc  quoắc  quoắc";
$objectOwl->food         = "chim bé";
$objectOwl->speed        = "30km/h";
$objectOwl->weight       = "3kg";
$objectCat               = new Cat;
$objectCat->image        = "9ff85c8aa3cd4670ae6ac08c4327deaf-1920.png" ;
$objectCat->name         = "THE CAT" ;
$objectCat->say          = "mèo uuu mèo uuu mèo mèo";
$objectCat->food         = "chuột và cá, thịt chính";
$objectCat->speed        = "30km/h";
$objectCat->weight       = "3kg";
$objectPanther           = new Panther;
$objectPanther->image    = "Bao.jpg";
$objectPanther->name     = "THE PANTHER";
$objectPanther->food     = "thịt";
$objectPanther->speed    = "100km/h";
$objectPanther->weight   = "40kg";
$objectPanther->say      = "gừ gừm gừm gừm gừm";
$objectDog               = new Dog;
$objectDog->image        = "doan-van-tham-khao-so-10-530005.jpg";
$objectDog->name         = "THE DOG";
$objectDog->food         = "thịt";
$objectDog->say          = "gâu gâu uhuhuhuhu";
$objectDog->speed        = "30km/h";
$objectDog->weight       = "20kg";
$objectLion              = new Lion;
$objectLion->image       = "lion-king-1-1563155068176555217978-15637834089391350227836-crop-15637834158711662738000.jpeg";
$objectLion->name        = "KING LION";
$objectLion->food        = "thịt";
$objectLion->say         = "goafc goafc goafc goafc";
$objectLion->speed       = "60km/h";
$objectLion->weight      = "60kg";
$objectTiger             = new Tiger;
$objectTiger->image      = "ho_an_thit_con_1_QBEO.png";
$objectTiger->name       = "THE TIGER";
$objectTiger->food       = "thịt";
$objectTiger->speed      = "70km/h";
$objectTiger->say        = "gừm gừm gừm gừm uhuhuhuhuhu";
$objectTiger->weight     = "80kg";
$objectEagle             = new Eagle;
$objectEagle->image      = "v2-72c732297cdf5d1291c101bed819cda3720w-16220189095601127267370.jpg";
$objectEagle->name       = "King Eagle";
$objectEagle->food       = "thịt";
$objectEagle->speed      = "70km/h";
$objectEagle->say        = "DIW DIW DIW DIWIN DIW DIW DIW";
$objectEagle->weight     = "3kg";
$objectDove              = new Dove;
$objectDove->image       = "20150923114929-cc4b.jpg";
$objectDove->name        = "THE DOVE";
$objectDove->speed       = "10km/h";
$objectDove->say         = "la la laa laa la ala ala";
$objectDove->weight      = "30kg";
$objectDove->food        = "sâu,bọ, bánh mì,cơm";
$objectDinosaure         = new Dinosaure;
$objectDinosaure->image  = "khung-long-khong-lo-9341-1628910694.jpg";
$objectDinosaure->name   = "THE KING DINOSAURE";
$objectDinosaure->speed  = "25km/h";
$objectDinosaure->weight = "120kg";
$objectDinosaure->say    = "uhuhuhuhuhuh";
$objectDinosaure->food   = "cỏ, thực vật";
$objects[]               = $objectDinosaure;
$objects[]               = $objectDog;
$objects[]               = $objectDove;
$objects[]               = $objectPanther;
$objects[]               = $objectEagle;
$objects[]               = $objectTiger;
$objects[]               = $objectCat;
$objects[]               = $objectLion;
$objects[]               = $objectOwl;
// echo "<pre>";
// print_r($objects);
// echo "</pre>";
include_once("html.php");

