<?php
namespace product;
include_once "sample.php";
include_once "product1.php";
use sample\Sample;
use product1\Product;
$objectProduct      = [];
$notebook           = new product;
$notebook->name     = "notebook" ;
$notebook->image    = "bd9022ebb668698d13a8a5262a511367.jpg" ;
$notebook->price    = "20.000 VND" ;
$notebook->button   = "mua" ;
$eraser             = new product;
$PencilCase         = new product;
$ruler              = new product;
$pen                = new product;
$ruler->name        = "ruler";
$ruler->image       = "thuoc_20cm_tq_86b51bffc0e24d858736e3ca03166279.jpg";
$ruler->price       = "20.000 VND";
$ruler->button      = "mua";
$PencilCase->name   = "PencilCase";
$PencilCase->image  = "unnamed.jpg";
$PencilCase->price  = "25.000 VND";
$PencilCase->button = "mua";
$eraser->name       = "eraser";
$eraser->price      = "10.000 VND";
$eraser->button     = "mua" ;
$eraser->image      = "ea1a0127bef73bb3b607d7364f8288c6.jfif";
$pen->name          = "pen";
$pen->price         = "40.000 VND";
$pen->button        = "mua" ;
$pen->image         = "but_tl0271_428e9bcba72a48b7a12ca7d3a3821971.jpg";
$pencil             = new Product;
$pencil->name       = "pencil";
$pencil->image      = "1466669551002_8915517.jpg";
$pencil->price      = "36.000 VND";
$pencil->button     = "mua";
$objectProduct[]    = $pencil;
$objectProduct[]    = $pen;
$objectProduct[]    = $eraser;
$objectProduct[]    = $PencilCase;
$objectProduct[]    = $ruler;
$objectProduct[]    = $notebook;

// echo "<pre>";
// print_r($objectProduct);
// echo "</pre>";
// echo "<pre>";
// print_r($pencil);
// echo "</pre>";
include_once "html.php";